import {it,expect,vi} from 'vitest';
import {createCipheriv} from 'node:crypto';
import Fastify from 'fastify';
import {createGmailService,gmailBody,GMAIL_SCOPES,registerGmailRoutes} from '../src/gmail.js';
const owner={userId:'owner-a',email:'fixture@example.test',accessToken:'fixture'},key=Buffer.alloc(32,2);
function encrypted(namespace='gmail'){const iv=Buffer.alloc(12,3),c=createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from('zundamon-'+namespace+':'+owner.userId));const bytes=Buffer.concat([c.update(JSON.stringify({refreshToken:'fixture'})),c.final()]);return Buffer.concat([iv,c.getAuthTag(),bytes]).toString('base64');}
function setup(){const rpc=vi.fn(async()=>({generation:'v1',payload:encrypted()}));const http=vi.fn(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'fixture',token_type:'Bearer',scope:GMAIL_SCOPES.join(' ')}):Response.json({messages:[]}));return {rpc,http,service:createGmailService({key,clientId:'fixture',clientSecret:'fixture',redirectUri:'https://example.test/callback',rpc,fetch:http as typeof fetch})};}
it('uses Gmail-only readonly scope and a separate opaque PKCE state',async()=>{const t=setup();const u=new URL(await t.service.begin(owner));expect(u.searchParams.get('scope')).toBe(GMAIL_SCOPES.join(' '));expect(u.searchParams.get('scope')).not.toContain('gmail.send');expect(u.searchParams.get('state')).toMatch(/^gmail\./);expect(u.searchParams.get('code_challenge_method')).toBe('S256');expect(await t.service.complete('code','drive.invalid')).toBe(false);});
it('cannot reuse Drive credentials or continue after disconnection',async()=>{const t=setup();t.rpc.mockResolvedValueOnce({generation:'v1',payload:encrypted('drive')});await expect(t.service.search(owner,'in:inbox')).rejects.toThrow();expect(t.http).not.toHaveBeenCalled();t.rpc.mockResolvedValueOnce({generation:'v1',payload:encrypted()}).mockResolvedValueOnce({generation:'v2',payload:encrypted()});await expect(t.service.search(owner,'in:inbox')).rejects.toThrow('gmail_disconnected');});
it('keeps search bounded and fetches metadata without changing read status',async()=>{const t=setup();t.http.mockImplementation(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'fixture',token_type:'Bearer'}):String(url).includes('/messages/ab')?Response.json({id:'ab',threadId:'cd',payload:{headers:[{name:'Subject',value:'Test'},{name:'From',value:'sender@example.test'}]}}):Response.json({messages:[{id:'ab',threadId:'cd'}],nextPageToken:'next'}));const result=await t.service.search(owner,'from:sender@example.test');expect(result.messages[0]?.subject).toBe('Test');expect(result.nextPageToken).toBe('next');const calls=t.http.mock.calls.filter(c=>!String(c[0]).includes('/token'));expect(new URL(String(calls[0]?.[0])).searchParams.get('maxResults')).toBe('10');expect(new URL(String(calls[1]?.[0])).searchParams.get('format')).toBe('metadata');});
it('prefers plain MIME text, drops attachments, and converts HTML without loading content',()=>{const encoded=(s:string)=>Buffer.from(s).toString('base64url');expect(gmailBody({parts:[{mimeType:'text/plain',body:{data:encoded('Hello')}},{mimeType:'text/html',body:{data:encoded('<p>duplicate</p>')}},{mimeType:'text/plain',filename:'private.txt',body:{data:encoded('attachment')}}]}).text).toBe('Hello');const html=gmailBody({mimeType:'text/html',body:{data:encoded('<script>secret()</script><img src="https://example.test/track"><p>Hello &amp; welcome</p>')}});expect(html.text).toBe('Hello & welcome');});
it('rejects unsafe ids and unauthenticated routes; has no send route',async()=>{const t=setup();await expect(t.service.read(owner,'../profile')).rejects.toThrow();expect(t.http).not.toHaveBeenCalled();const app=Fastify();registerGmailRoutes(app,t.service);expect((await app.inject({url:'/api/gmail/status'})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/gmail/read',payload:{id:'ab'}})).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/gmail/send',payload:{}})).statusCode).toBe(404);await app.close();});

it('decodes declared Japanese mail charsets and fails closed on unknown encoding',()=>{
 const part={mimeType:'text/plain',headers:[{name:'Content-Type',value:'text/plain; charset="shift_jis"'}],body:{data:Buffer.from([0x93,0xfa,0x96,0x7b]).toString('base64url')}};
 expect(gmailBody(part).text).toBe('日本');
 expect(()=>gmailBody({...part,headers:[{name:'Content-Type',value:'text/plain; charset=unknown-invalid'}]})).toThrow('gmail_encoding_unavailable');
});
