import {it,expect,vi} from 'vitest';
import {createGoogleWrites,encodeMail,writeInput} from '../src/google-writes';
const owner={userId:'one',accessToken:'fixture'},other={userId:'other',accessToken:'fixture'};
function setup(){const records=new Map<string,any>();const rpc=vi.fn(async(o:string,action:string,args:any)=>{const k=o+args.id,r=records.get(k);if(action==='prepare'){const row={...args,state:'prepared'};records.set(k,row);return row;}if(action==='claim'){if(r?.state!=='prepared')return null;r.state='executing';}if(action==='cancel'&&r?.state==='prepared')r.state='cancelled';if(action==='finish')Object.assign(r,args);return r?{...r}:null;});const writeAccess=vi.fn(async()=>({token:'fake',generation:'1',subject:'google-owner'}));const http=vi.fn(async(url:any,opts:any)=>opts.method==='POST'?Response.json({id:'abcd'}):String(url).endsWith('/profile')?Response.json({emailAddress:'sender@example.test'}):Response.json({name:'My folder',mimeType:'application/vnd.google-apps.folder',capabilities:{canAddChildren:true}}));return {rpc,http,writeAccess,service:createGoogleWrites({gmail:{writeAccess} as any,drive:{writeAccess} as any,key:Buffer.alloc(32,1),rpc,fetch:http as any})};}
it('requires exact preparation and performs one send across concurrent/replayed confirmations',async()=>{const t=setup();const p=await t.service.prepare(owner,{kind:'gmail',to:'to@example.test',title:'日本語',body:'確認しました'});expect(t.http.mock.calls.filter(c=>c[1].method==='POST')).toHaveLength(0);expect(p.from).toBe('sender@example.test');await expect(t.service.confirm(other,p.id)).rejects.toThrow();await Promise.all([t.service.confirm(owner,p.id),t.service.confirm(owner,p.id)]);await t.service.confirm(owner,p.id);expect(t.http.mock.calls.filter(c=>c[1].method==='POST')).toHaveLength(1);expect((await t.service.status(owner,p.id)).state).toBe('succeeded');});
it('rejects stale connections, injected headers and nonexistent folder access',async()=>{const t=setup();expect(writeInput.safeParse({kind:'gmail',to:'a@example.test\r\nBcc: b@example.test',title:'a',body:'b'}).success).toBe(false);const p=await t.service.prepare(owner,{kind:'drive',folderId:'root',title:'memo.txt',body:'hello'});t.writeAccess.mockResolvedValue({token:'fake',generation:'2',subject:'google-owner'});await expect(t.service.confirm(owner,p.id)).rejects.toThrow('connection_changed');expect(t.http.mock.calls.filter(c=>c[1].method==='POST')).toHaveLength(0);});
it('never retries ambiguous external outcomes',async()=>{const t=setup();const p=await t.service.prepare(owner,{kind:'gmail',to:'a@example.test',title:'test',body:'text'});t.http.mockRejectedValue(Error('timeout'));expect((await t.service.confirm(owner,p.id)).state).toBe('unknown');await t.service.confirm(owner,p.id);expect(t.http).toHaveBeenCalledTimes(2);});
it('encodes Japanese mail safely as MIME base64',()=>{const raw=Buffer.from(encodeMail({from:'a@example.test',to:'b@example.test',title:'日本語',body:'こんにちは'}),'base64url').toString();expect(raw).toContain('Subject: =?UTF-8?B?');expect(raw).toContain(Buffer.from('こんにちは').toString('base64'));});
it('creates a new text file with the confirmed parent and rejects an unwritable folder',async()=>{const t=setup();const p=await t.service.prepare(owner,{kind:'drive',folderId:'selected_folder',title:'メモ.txt',body:'本文'});await t.service.confirm(owner,p.id);const call=t.http.mock.calls.find(c=>c[1].method==='POST')!;expect(String(call[0])).toBe('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id');expect(call[1].body).toContain('"parents":["selected_folder"]');expect(call[1].body).toContain('本文');const denied=setup();denied.http.mockResolvedValue(Response.json({mimeType:'application/vnd.google-apps.folder',capabilities:{canAddChildren:false}}));await expect(denied.service.prepare(owner,{kind:'drive',folderId:'folder',title:'x.txt',body:'x'})).rejects.toThrow('folder_unavailable');expect(denied.rpc).not.toHaveBeenCalled();});
it('does not send cancelled preparations',async()=>{const t=setup();const p=await t.service.prepare(owner,{kind:'gmail',to:'a@example.test',title:'test',body:'text'});await t.service.cancel(owner,p.id);expect((await t.service.confirm(owner,p.id)).state).toBe('cancelled');expect(t.http.mock.calls.filter(c=>c[1].method==='POST')).toHaveLength(0);});
