import {describe,it,expect,vi} from 'vitest';
import {createCipheriv} from 'node:crypto';
import {createGoogleDriveService,DRIVE_SCOPES} from '../src/google-drive.js';
const owner={userId:'00000000-0000-4000-8000-000000000001',email:'owner@example.test',accessToken:'fixture'};
const key=Buffer.alloc(32,2);
function encrypted(){const iv=Buffer.alloc(12,3),c=createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from('zundamon-drive:'+owner.userId));const bytes=Buffer.concat([c.update(JSON.stringify({refreshToken:'fixture'})),c.final()]);return Buffer.concat([iv,c.getAuthTag(),bytes]).toString('base64');}
function setup(){const rpc=vi.fn(async()=>({generation:'v1',payload:encrypted()}));const http=vi.fn(async(url:any)=>String(url).includes('oauth2.googleapis.com/token')?Response.json({access_token:'fixture-access',token_type:'Bearer',scope:DRIVE_SCOPES.join(' ')}):Response.json({files:[]}));return {rpc,http,service:createGoogleDriveService({key,clientId:'fixture',clientSecret:'fixture',redirectUri:'https://example.test/callback',rpc,fetch:http as typeof fetch})};}
describe('Drive owner read',()=>{
 it('requests readonly Drive permission with PKCE and opaque one-time state',async()=>{const t=setup();const u=new URL(await t.service.begin(owner));expect(u.searchParams.get('scope')).toBe(DRIVE_SCOPES.join(' '));expect(u.searchParams.get('code_challenge_method')).toBe('S256');expect(u.searchParams.get('state')).toMatch(/^drive\./);expect(u.searchParams.get('state')).not.toContain(owner.userId);expect(t.rpc.mock.calls[0]?.[0]).toBe(owner.userId);});
 it('escapes search input and keeps pagination',async()=>{const t=setup();await t.service.search(owner,"a' or trashed=true",'next');const u=new URL(String(t.http.mock.calls.at(-1)?.[0]));expect(u.hostname).toBe('www.googleapis.com');expect(u.searchParams.get('q')).toContain("a\\' or trashed=true");expect(u.searchParams.get('pageToken')).toBe('next');});
 it('does not read files after connection generation changes during refresh',async()=>{const t=setup();t.rpc.mockResolvedValueOnce({generation:'v1',payload:encrypted()}).mockResolvedValueOnce({generation:'v2',payload:encrypted()});await expect(t.service.search(owner,'test')).rejects.toThrow('drive_disconnected');expect(t.http).toHaveBeenCalledTimes(1);});
 it('rejects path traversal and unsupported formats',async()=>{const t=setup();await expect(t.service.read(owner,'../secret')).rejects.toThrow();expect(t.http).not.toHaveBeenCalled();t.http.mockImplementation(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'fixture',token_type:'Bearer'}):Response.json({id:'file',name:'binary',mimeType:'application/octet-stream'}));await expect(t.service.read(owner,'file')).rejects.toThrow('drive_unsupported_type');});
 it('exports a Google document as bounded plain text',async()=>{const t=setup();t.http.mockImplementation(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'fixture',token_type:'Bearer'}):String(url).includes('/export')?new Response('本文'):Response.json({id:'file',name:'資料',mimeType:'application/vnd.google-apps.document'}));expect(await t.service.read(owner,'file')).toMatchObject({text:'本文',truncated:false});});
 it('rejects malformed callback state before any repository access',async()=>{const t=setup();expect(await t.service.complete('code','forged')).toBe(false);expect(t.rpc).not.toHaveBeenCalled();});
});
it('finds videos by folder membership even when filenames omit the folder name',async()=>{
 const t=setup();t.http.mockImplementation(async(url:any)=>{if(String(url).includes('/token'))return Response.json({access_token:'fixture',token_type:'Bearer'});const q=new URL(String(url)).searchParams.get('q')??'';return q.includes("mimeType = 'application/vnd.google-apps.folder'")?Response.json({files:[{id:'folder_1',name:'Demo',mimeType:'application/vnd.google-apps.folder'}]}):Response.json({files:[{id:'movie_1',name:'IMG_123.MOV',mimeType:'video/quicktime'}],nextPageToken:'page2'});});
 const result=await t.service.search(owner,'Demo',undefined,'video');expect(result.files[0]?.name).toBe('IMG_123.MOV');const q=new URL(String(t.http.mock.calls.at(-1)?.[0])).searchParams.get('q');expect(q).toContain("'folder_1' in parents");expect(q).toContain("mimeType contains 'video/'");expect(result.nextPageToken).toBe('page2');
 await t.service.search(owner,'Demo','page2','video');expect(new URL(String(t.http.mock.calls.at(-1)?.[0])).searchParams.get('pageToken')).toBe('page2');
});
it('rejects incomplete folder lookup instead of presenting unrelated media as the result',async()=>{const t=setup();t.http.mockImplementation(async(url:any)=>String(url).includes('/token')?Response.json({access_token:'fixture',token_type:'Bearer'}):Response.json({files:[],nextPageToken:'remaining-folders'}));await expect(t.service.search(owner,'Demo',undefined,'video')).rejects.toThrow('drive_incomplete_search');});
