import type {WritesApi} from './google-writes';
import {GmailCard} from './GmailCard';
import type {GmailApi} from './gmail';
import type {DriveApi} from './google-drive';
import { useEffect, useRef, useState } from 'react';
import { lifeMapsUrl, type LifeCard, type GoogleAssistantItem, type GoogleAssistantOperation } from '@yui/domain';
import type { LifeServicesApi } from './life-services';
import './life-services.css';
export function lifeLocalDateTime(value:string):string {const date=new Date(value);if(!Number.isFinite(date.getTime()))return '';const pad=(n:number)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function displayDate(value:string|undefined):string {if(!value)return '';const onlyDay=/^\d{4}-\d{2}-\d{2}$/.test(value);const date=new Date(onlyDay?`${value}T00:00:00`:value);return Number.isFinite(date.getTime())?new Intl.DateTimeFormat('ja-JP',onlyDay?{year:'numeric',month:'long',day:'numeric'}:{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(date):value;}
function Fields({value}:{value:Record<string,unknown>|null}) { const labels:Record<string,string>={title:'題名',notes:'メモ',start:'開始',end:'終了',due:'期限日',completed:'完了'};return <dl>{Object.entries(labels).filter(([k])=>value&&Object.hasOwn(value,k)).map(([k,label])=><div key={k}><dt>{label}</dt><dd>{value?.[k]===null?'なし':typeof value?.[k]==='boolean'?(value[k]?'完了':'未完了'):['start','end','due'].includes(k)?displayDate(String(value?.[k])):String(value?.[k])}</dd></div>)}</dl>; }
const stateText={prepared:'確認待ち',executing:'実行状態を確認中',succeeded:'変更を照合しました',cancelled:'取消済み',expired:'確認期限が切れました',conflict:'対象が変わっています。下書きを作り直してください',unknown:'結果不明です。再実行せず状態を確認してください'};
function operationStateText(op:GoogleAssistantOperation):string {return op.state==='succeeded'?(op.request.action==='delete'?'削除しました':op.request.action==='create'?'登録しました':'変更しました'):stateText[op.state];}
export function LifeCardView({card,api,driveApi,gmailApi,writesApi,onCardChange}:{card:LifeCard;api:LifeServicesApi;driveApi?:DriveApi;gmailApi?:GmailApi;writesApi?:WritesApi;onCardChange?:(card:LifeCard)=>void|Promise<void>}) {
 const [current,setCurrent]=useState(card),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState(false),[edit,setEdit]=useState<GoogleAssistantItem|null>(null),[title,setTitle]=useState(''),[notes,setNotes]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[due,setDue]=useState('');
 const [notice,setNotice]=useState('');
 const currentRef=useRef(card),changeRef=useRef(onCardChange);changeRef.current=onCardChange;
 const mounted=useRef(false),running=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const cardJson=JSON.stringify(card);
 useEffect(()=>{currentRef.current=card;setCurrent(card);},[cardJson]);
 async function replaceCard(next:LifeCard){if(!mounted.current||JSON.stringify(currentRef.current)===JSON.stringify(next))return;await changeRef.current?.(next);if(!mounted.current)return;currentRef.current=next;setCurrent(next);}
 const operationId=card.kind==='google-operation'?card.operation.operationId:null;
 useEffect(()=>{if(!operationId)return;let active=true;setVerified(false);api.operation(operationId).then(async operation=>{if(active){await replaceCard({kind:'google-operation',operation});if(active)setVerified(true);}}).catch(()=>{if(active)setError('現在の操作状態を確認できません。状態を確認してください。');});return()=>{active=false;};},[api,operationId]);
 async function run(fn:()=>Promise<void>){if(!mounted.current||running.current)return;running.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(cause){if(mounted.current){setVerified(false);setError(currentRef.current.kind.startsWith('gmail-')?'メールを確認できませんでした。もう一度試してください。':currentRef.current.kind.startsWith('drive-')?(cause instanceof Error?cause.message:'ファイルを読み取れませんでした。'):'結果を確認できませんでした。変更は繰り返さず、状態を確認してください。');}}finally{running.current=false;if(mounted.current)setBusy(false);}}
 const showOp=async(operation:GoogleAssistantOperation)=>{await replaceCard({kind:'google-operation',operation});if(mounted.current)setVerified(true);};
 return <section className={`life-card${(current.kind==='drive-results'||current.kind.startsWith('gmail-'))?' drive-links chat-message-bubble':''}`} aria-label="生活サービスの結果" aria-busy={busy}>
 {(current.kind==='gmail-results'||current.kind==='gmail-content'||current.kind==='gmail-draft')&&<GmailCard writesApi={writesApi} card={current} api={gmailApi} busy={busy} run={run} replace={replaceCard}/>}
 {current.kind==='drive-results'&&<><ul>{current.result.files.map(file=><li key={file.id}><a href={`https://drive.google.com/file/d/${encodeURIComponent(file.id)}/view`} target="_blank" rel="noopener noreferrer">{file.mimeType.startsWith('video/')?'▶ 動画を開く':file.mimeType.startsWith('image/')?'写真を開く':'ファイルを開く'}（{file.name}） ↗</a>{(file.mimeType==='application/pdf'||file.mimeType==='application/vnd.google-apps.document'||file.mimeType.startsWith('text/')||['application/json','application/xml'].includes(file.mimeType))&&<button disabled={busy||!driveApi} onClick={()=>void run(async()=>{await replaceCard({kind:'drive-content',content:await driveApi!.read(file.id)});})}>内容を読む</button>}</li>)}</ul>{current.result.nextPageToken&&<button disabled={busy||!driveApi} onClick={()=>void run(async()=>{await replaceCard({...current,result:await driveApi!.search(current.query,current.result.nextPageToken,current.mediaType)});})}>続きを見る</button>}</>}
 {current.kind==='drive-content'&&<><strong>{current.content.file.name}</strong><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:'24rem',overflow:'auto'}}>{current.content.text||'本文は空です。'}</p>{current.content.truncated&&<p>長い文書のため、先頭の一部を表示しています。</p>}<a href={`https://drive.google.com/file/d/${encodeURIComponent(current.content.file.id)}/view`} target="_blank" rel="noopener noreferrer">Google Driveで開く</a></>}
 {current.kind==='google-items'&&<><strong>{current.sourceTitle}</strong><small>取得: {displayDate(current.result.fetchedAt)}</small>{current.result.timeMin&&<p>{displayDate(current.result.timeMin)} 〜 {displayDate(current.result.timeMax)}</p>}<ul>{current.result.items.map(item=><li key={item.id}><strong>{item.title}</strong><p>{displayDate(item.start??item.due)}{item.end?` 〜 ${displayDate(item.end)}`:''}</p>{item.service==='tasks'&&item.notes&&<details><summary>メモを表示</summary><p>{item.notes}</p></details>}{!item.unsupported&&<button disabled={busy} onClick={()=>{setEdit(item);setTitle(item.title);setNotes(item.notes??'');setStart(lifeLocalDateTime(item.start??''));setEnd(lifeLocalDateTime(item.end??''));setDue(item.due??'');}}>変更の下書き</button>}{item.service==='calendar'&&!item.unsupported&&<button disabled={busy} onClick={()=>void run(async()=>showOp(await api.prepare({service:item.service,sourceId:item.sourceId,itemId:item.id,version:item.version,action:'delete',changes:{}})))}>削除の確認へ</button>}{item.service==='tasks'&&<button disabled={busy} onClick={()=>void run(async()=>showOp(await api.prepare({service:item.service,sourceId:item.sourceId,itemId:item.id,version:item.version,action:'complete',changes:{completed:!item.completed}})))}>{item.completed?'未完了に戻す下書き':'完了にする下書き'}</button>}</li>)}</ul>{!current.result.items.length&&<p>対象はありません。</p>}{current.result.nextPageToken&&<><p>続きがあります。この表示は全件ではありません。</p><button disabled={busy} onClick={()=>void run(async()=>{await replaceCard({...current,result:await api.list({service:current.result.service,sourceId:current.result.sourceId,pageToken:current.result.nextPageToken,...(current.result.timeMin?{timeMin:current.result.timeMin,timeMax:current.result.timeMax}:{})})});})}>次の項目</button></>}<button disabled={busy} onClick={()=>void run(async()=>{await replaceCard({...current,result:await api.list({service:current.result.service,sourceId:current.result.sourceId,...(current.result.timeMin?{timeMin:current.result.timeMin,timeMax:current.result.timeMax}:{})})});})}>更新</button></>}
 {edit&&<form onSubmit={e=>{e.preventDefault();void run(async()=>{await showOp(await api.prepare({service:edit.service,sourceId:edit.sourceId,itemId:edit.id,version:edit.version,action:'update',changes:{title,notes,...(edit.service==='tasks'?{due:due||null}:{start:new Date(start).toISOString(),end:new Date(end).toISOString()})}}));if(mounted.current)setEdit(null);});}}><label>題名<input value={title} maxLength={1024} onChange={e=>setTitle(e.target.value)}/></label><label>メモ<textarea value={notes} maxLength={8000} onChange={e=>setNotes(e.target.value)}/></label>{edit.service==='tasks'?<label>期限日<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label>:<><label>開始<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>終了<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<button disabled={busy||!title.trim()}>変更内容を確認</button><button type="button" onClick={()=>setEdit(null)}>閉じる</button></form>}
 {current.kind==='google-operation'&&<><strong>{operationStateText(current.operation)}</strong><p>対象: {current.operation.before?.title??current.operation.request.changes.title} ／ {current.operation.request.service==='calendar'?'Googleカレンダー':'Google Tasks'}</p><p>変更前</p><Fields value={current.operation.before}/><p>{current.operation.request.action==='delete'?(current.operation.state==='succeeded'?'削除した予定':'この予定を削除します'):'変更後（変更する項目）'}</p><Fields value={current.operation.request.changes}/><p>確認期限: {displayDate(current.operation.expiresAt)}</p>{current.operation.state==='prepared'&&<><button disabled={busy||!verified||Date.parse(current.operation.expiresAt)<=Date.now()} onClick={()=>void run(async()=>showOp(await api.confirm(current.operation.operationId,current.operation.signature)))}>{current.operation.request.action==='delete'?'この予定を削除':current.operation.request.action==='create'?'この内容で追加':'この内容で変更'}</button><button disabled={busy||!verified} onClick={()=>void run(async()=>showOp(await api.cancel(current.operation.operationId)))}>やめる</button></>}<button disabled={busy} onClick={()=>void run(async()=>{const operation=await api.operation(current.operation.operationId);await showOp(operation);if(mounted.current)setNotice(`確認しました：${operationStateText(operation)}${operation.state==='unknown'?'。自動で再実行はせず、Googleカレンダーで予定を確認してください。':''}`);})}>{busy?'確認中…':'状態を確認'}</button></>}
 {current.kind==='weather'&&<><strong>{current.forecast.home.label}周辺の天気</strong>{current.forecast.days.map(d=><p key={d.date}>{displayDate(d.date)} ／ {d.temperatureMin}〜{d.temperatureMax}℃ ／ 降水確率 {d.precipitationProbability}%</p>)}<p>取得: {displayDate(current.forecast.fetchedAt)}</p><small>{current.forecast.attribution}</small></>}
 {current.kind==='maps'&&<><p>{current.origin?`${current.origin}周辺`:'Googleマップで現在地を指定'} → {current.destination}</p><p>移動手段: {{driving:'車',walking:'徒歩',bicycling:'自転車',transit:'公共交通'}[current.travelMode]}</p><a href={lifeMapsUrl(current)} target="_blank" rel="noopener noreferrer">Googleマップで道順を見る</a><small>開くと出発地と目的地をGoogleへ送ります。</small></>}
 {current.kind==='home-candidates'&&<><strong>自宅・地域の候補</strong><p>{current.candidates.length?'保存する地域を選んでください。':'候補が見つかりませんでした。市区町村の名前でユイに伝えてください。'}</p>{current.candidates.map((h,i)=><button disabled={busy} key={i} onClick={()=>void run(async()=>{const settings=await api.getSettings();if(!mounted.current)return;if(settings.revision!==current.revision)throw new Error('conflict');await api.saveSettings({...settings,home:h});if(mounted.current)setError('地域を保存しました。');})}>{h.label}（{h.precision==='station'?'駅周辺':'市区町村'}）を保存</button>)}</>}
 {notice&&<p role="status">{notice}</p>}
 {error&&<p role="status">{error}</p>}
 </section>;
}
