import {test,expect} from 'playwright/test';
test('2D opens directly, speaks new replies, retains history and closes at phone sizes',async({page})=>{
 await page.goto('/test/fixtures/zundamon.fixture.html');
 await page.getByRole('button',{name:'ユイの姿を選ぶ'}).click();
 await expect(page.locator('.avatar-conversation')).toBeVisible();
 await expect(page.locator('.live2d-avatar-stage')).toHaveAttribute('data-state','ready');
 await page.getByRole('textbox',{name:'メッセージ'}).fill('こんにちは');
 await page.getByRole('button',{name:'メッセージを送信',exact:true}).click();
 await expect.poll(()=>page.evaluate(()=>(window as any).lastSpokenText)).toContain('ローカルの試作');
 await page.getByRole('textbox',{name:'メッセージ'}).blur();
 await expect(page.getByText('ずんだもんの姿を表示する、ローカルの試作だよ。')).toBeVisible();
 await expect(page.locator('.chat-message-bubble').last()).toHaveCSS('color','rgb(255, 255, 255)');
 await page.screenshot({path:'test-results/avatar-conversation-390.png'});
 await page.getByRole('button',{name:'履歴を広げる'}).click();
 await expect(page.locator('.history-expanded')).toBeVisible();
 await page.getByRole('button',{name:'音声ON',exact:true}).click();
 await page.evaluate(()=>{(window as any).lastSpokenText=null;});
 await page.getByRole('textbox',{name:'メッセージ'}).fill('もう一度');
 await page.getByRole('button',{name:'メッセージを送信',exact:true}).click();
 await expect(page.getByText('ずんだもんの姿を表示する、ローカルの試作だよ。')).toHaveCount(2);
 expect(await page.evaluate(()=>(window as any).lastSpokenText)).toBeNull();
 await page.getByRole('button',{name:'通常トークに戻る'}).click();
 await expect(page.locator('.avatar-conversation')).toHaveCount(0);
 await expect(page.getByText('ずんだもんの姿を表示する、ローカルの試作だよ。')).toHaveCount(2);
 await page.setViewportSize({width:320,height:740});
 await page.getByRole('button',{name:'ユイの姿を選ぶ'}).click();
 await expect(page.locator('.live2d-avatar-stage')).toHaveAttribute('data-state','ready');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/avatar-conversation-320.png'});
});
