import {test,expect} from 'playwright/test';
import {mkdir} from 'node:fs/promises';
test('390px actual App keeps life services in talk and persists prepared operations',async({page})=>{
 const external:string[]=[];await page.route('**/*',route=>{if(new URL(route.request().url()).hostname!=='127.0.0.1'||new URL(route.request().url()).pathname.startsWith('/api/')){external.push(route.request().url());return route.abort();}return route.continue();});
 await page.goto('/test/fixtures/talk-life-services.fixture.html');await expect(page.getByRole('main',{name:'ユイとの継続トーク'})).toBeVisible();
 await expect(page.getByRole('button',{name:/^(Home|News|ホーム|ニュース)$/})).toHaveCount(0);
 await expect(page.locator('.chat-header')).toHaveCSS('background-color','rgb(255, 255, 255)');
 await page.getByRole('textbox',{name:'メッセージ',exact:true}).focus();
 await expect(page.locator('.composer-shell')).toHaveCSS('outline-style','none');
 const shell=await page.locator('.composer-shell').boundingBox();expect(shell).not.toBeNull();expect(844-shell!.y-shell!.height).toBeGreaterThanOrEqual(31);

 await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('button',{name:'検索',exact:true}).click();await expect(page.getByRole('searchbox',{name:'チャット履歴を検索'})).toBeVisible();await page.getByRole('button',{name:'検索を閉じる'}).click();
 await page.getByRole('button',{name:'メニューを開く'}).click();await expect(page.getByRole('button',{name:'アプリ設定',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'表示スタイル',exact:true}).click();await expect(page.getByRole('dialog',{name:'表示スタイル'})).toBeVisible();await expect(page.getByRole('radio',{name:'デフォルト'})).toBeVisible();await page.getByRole('button',{name:'トークへ戻る'}).click();await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('button',{name:'このアプリについて',exact:true}).click();await expect(page.getByRole('dialog',{name:'このアプリについて'})).toBeVisible();await page.getByRole('button',{name:'トークへ戻る'}).click();
 await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('button',{name:'Google連携',exact:true}).click();await expect(page.getByRole('dialog',{name:'Google連携'})).toBeVisible();await page.getByRole('button',{name:'参照先を取得'}).first().click();await page.getByRole('button',{name:'仕事を選択'}).click();await expect(page.getByRole('status')).toContainText('保存しました');await page.getByRole('button',{name:'閉じる',exact:true}).click();
 await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('button',{name:'メモリ',exact:true}).click();await page.getByRole('textbox',{name:'職業',exact:true}).fill('架空の仕事');await page.getByRole('textbox',{name:'あなたについての詳細',exact:true}).fill('架空の好み\n散歩が好き');await page.getByRole('button',{name:'地域を選ぶ',exact:true}).click();await page.getByRole('textbox',{name:'地域名'}).fill('架空市');await page.getByRole('button',{name:'候補を探す'}).click();await page.getByRole('button',{name:'架空市（周辺）を保存'}).click();await expect(page.getByText('保存地域: 架空市')).toBeVisible();await mkdir('test-results/talk-life-services',{recursive:true});await page.screenshot({path:'test-results/talk-life-services/settings.png',fullPage:true});await page.getByRole('button',{name:'閉じる',exact:true}).click();await expect(page.getByRole('textbox',{name:'職業',exact:true})).toHaveValue('架空の仕事');await page.getByRole('button',{name:'保存する',exact:true}).click();await expect(page.getByRole('status')).toHaveText('保存しました。');await page.screenshot({path:'test-results/talk-life-services/memory.png',fullPage:true});await page.getByRole('button',{name:'トークへ戻る'}).click();
 const send=async(text:string)=>{await page.getByRole('textbox',{name:'メッセージ',exact:true}).fill(text);await page.getByRole('button',{name:'メッセージを送信',exact:true}).click();};
 await send('明日の仕事の予定は？');await page.getByRole('button',{name:'変更の下書き'}).click();await page.getByRole('textbox',{name:'題名',exact:true}).fill('架空の変更後');await page.getByRole('button',{name:'変更内容を確認'}).click();await expect(page.getByRole('button',{name:'この内容で変更'})).toBeEnabled();
 await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('fixture-chat')!).timeline.some((v:any)=>v.lifeCard?.kind==='google-operation'))).toBe(true);await page.reload();await expect(page.getByRole('button',{name:'この内容で変更'})).toBeEnabled();await page.getByRole('button',{name:'この内容で変更'}).click();await expect(page.getByText('変更を照合しました')).toBeVisible();await page.reload();await expect(page.getByText('変更を照合しました')).toBeVisible();await expect(page.getByRole('button',{name:'この内容で変更'})).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('fixture-confirms')!))).toBe(1);
 await send('家から東京駅への道');const maps=page.getByRole('link',{name:'Googleマップで道順を見る'});await expect(maps).toBeVisible();expect(new URL((await maps.getAttribute('href'))!).hostname).toBe('www.google.com');await send('今日の天気');await expect(page.getByText('架空市周辺の天気')).toBeVisible();await expect(page.getByText(/降水確率 60%/)).toBeVisible();await expect(page.locator('.life-card').last().locator('p').first()).toHaveCSS('background-image','none');await page.screenshot({path:'test-results/talk-life-services/talk.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(external).toEqual([]);
});
for(const width of [320,1280])test(`refreshed layout ${width}px and dark mode`,async({page})=>{
 await page.setViewportSize({width,height:844});await page.goto('/test/fixtures/talk-life-services.fixture.html');await expect(page.locator('.chat-screen')).toHaveCSS('background-color','rgb(250, 250, 250)');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('button',{name:'メモリ',exact:true}).click();await expect(page.getByRole('textbox',{name:'職業',exact:true})).toBeEnabled();await page.screenshot({path:`test-results/talk-life-services/memory-${width}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.emulateMedia({colorScheme:'dark'});await expect(page.getByRole('dialog',{name:'メモリ',exact:true})).toHaveCSS('background-color','rgb(27, 27, 30)');await page.getByRole('button',{name:'トークへ戻る'}).click();await expect(page.locator('.chat-screen')).toHaveCSS('background-color','rgb(27, 27, 30)');await page.screenshot({path:`test-results/talk-life-services/talk-dark-${width}.png`});
});
test('history reading collapses and restores composer without losing draft',async({page})=>{await page.goto('/test/fixtures/talk-life-services.fixture.html');for(let i=0;i<4;i++){await page.getByRole('textbox',{name:'メッセージ',exact:true}).fill('天気');await page.getByRole('button',{name:'メッセージを送信',exact:true}).click();await expect(page.locator('.life-card')).toHaveCount(i+1);}await page.locator('.chat-scroll-area').evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll'));});await expect(page.getByRole('button',{name:'メッセージを書く'})).toBeVisible();await page.screenshot({path:'test-results/talk-life-services/history.png'});await page.getByRole('button',{name:'メッセージを書く'}).click();await page.getByRole('textbox',{name:'メッセージ',exact:true}).fill('書きかけ');await page.locator('.chat-scroll-area').evaluate(el=>{el.scrollTop=0;el.dispatchEvent(new Event('scroll'));});await expect(page.getByRole('textbox',{name:'メッセージ',exact:true})).toHaveValue('書きかけ');expect(await page.locator('.chat-scroll-area').evaluate(el=>el.scrollTop)).toBeLessThan(10);});
