import { test, expect } from 'playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
const path = '/test/fixtures/zundamon.fixture.html';
const metrics = (page: import('playwright/test').Page) => page.evaluate(() => (window as any).avatarMetrics);
test('official model: select, Talk, mouth fixture, dispose and reopen at phone width', async ({ page, browserName }) => {
  await mkdir('test-results/zundamon', { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto(path + '?mouth=fixture');
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready', { timeout: 20000 });
  await page.screenshot({ path: 'test-results/zundamon/390-selection.png' });
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  const before = await metrics(page);
  await page.waitForTimeout(4500);
  const after = await metrics(page);
  expect(after.frames - before.frames).toBeLessThanOrEqual(141);
  expect(after.active).toBe(1);
  expect(after.mouthMax).toBeGreaterThan(0.7);
  expect(after.blinks).toBeGreaterThan(0);
  await page.screenshot({ path: 'test-results/zundamon/390-talk.png' });
  // Simulate the browser's visibility event, then verify real GL teardown/reload.
  await page.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'hidden' }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  const paused = (await metrics(page)).frames;
  await page.waitForTimeout(200);
  expect((await metrics(page)).frames).toBe(paused);
  await page.evaluate(() => { Object.defineProperty(document, 'visibilityState', { configurable: true, value: 'visible' }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.locator('.talk-avatar').evaluate(el => (el as HTMLElement).style.transform = 'translateY(-1200px)');
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  await page.locator('.talk-avatar').evaluate(el => (el as HTMLElement).style.transform = '');
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.getByRole('textbox', { name: 'メッセージ' }).fill('こんにちは');
  await page.getByRole('button', { name: 'メッセージを送信', exact: true }).click();
  await expect(page.getByText('ずんだもんの姿を表示する、ローカルの試作だよ。')).toBeVisible();
  await page.screenshot({ path: 'test-results/zundamon/390-talk.png' });
  await page.getByRole('button', { name: '通常トークに戻る' }).click();
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.getByRole('button', { name: '通常トークに戻る', exact: true }).click();
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  await page.setViewportSize({ width: 320, height: 740 });
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.locator('.talk-avatar .live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.screenshot({ path: 'test-results/zundamon/320-selection.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '通常トークに戻る', exact: true }).click();
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.locator('.live2d-avatar-stage')).toHaveAttribute('data-state', 'ready');
  await page.locator('canvas.live2d-avatar-canvas').evaluate((canvas: HTMLCanvasElement) => canvas.getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext());
  await expect(page.getByText('静止画で表示しています')).toBeVisible();
  await expect.poll(async () => (await metrics(page)).active).toBe(0);
  await page.getByRole('button', { name: '通常トークに戻る', exact: true }).click();
  expect(errors).toEqual([]);
  await writeFile(`test-results/zundamon/${browserName}-metrics.json`, JSON.stringify({ viewport: `${browserName} touch 390x844 DPR2; canvas cap1.5`, observationMs: 4500, frames: after.frames - before.frames, estimatedFps: (after.frames - before.frames) / 4.5, lifecycle: await metrics(page), errors, physicalIphoneMemory: 'NOT RUN' }, null, 2));
});
test('network failure shows the same character still and keeps Talk usable', async ({ page, browserName }) => {
  await page.route('**/live2d/zundamon/zundamon.moc3', route => route.abort());
  await page.goto(path);
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.getByText('静止画で表示しています')).toBeVisible();
  const image = page.getByRole('img', { name: 'ずんだもん' });
  expect(await image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true);
  await page.screenshot({ path: 'test-results/zundamon/390-fallback.png' });
  await page.getByRole('button', { name: '通常トークに戻る', exact: true }).click();
  await expect(page.getByRole('button', { name: 'ユイの姿を選ぶ' })).toBeVisible();
  expect((await metrics(page)).active).toBe(0);
});
test('reduced motion avoids all runtime requests', async ({ page, browserName }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const runtime: string[] = [];
  page.on('request', request => { if (/moc3|texture_00|yui-zundamon-bridge\.js/.test(request.url())) runtime.push(request.url()); });
  await page.goto(path);
  await page.getByRole('button', { name: 'ユイの姿を選ぶ' }).click();
  await expect(page.getByText('静止画で表示しています')).toBeVisible();
  expect(runtime).toEqual([]);
});
