import {useEffect,useState} from 'react';
import {EnvelopeSimple} from '@phosphor-icons/react';
import type {GmailApi} from '../gmail';
export function GmailConnection({api,navigate}:{api?:GmailApi;navigate:(url:string)=>void}){
 const [status,setStatus]=useState<{connected:boolean;available:boolean;writeEnabled?:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 useEffect(()=>{let active=true;if(api)api.status().then(s=>{if(active)setStatus(s);}).catch(()=>{if(active)setError('Gmailの接続状態を確認できませんでした。');});return()=>{active=false;};},[api]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch{setError('Gmailの接続を確認できませんでした。もう一度お試しください。');}finally{setBusy(false);}}
 return <section className="google-connection-card"><div className="google-connection-title"><EnvelopeSimple size={26}/><div><h2>Gmail</h2><span>{!api?'準備中':!status?'接続状態を確認中':status.connected?'接続済み':status.available?'未接続':'準備中'}</span></div></div><p>メールの検索・本文の確認・要約と、返信の下書きを作れます。</p>{status?.connected?<>{!status.writeEnabled&&<button className="google-connect-action" disabled={busy} onClick={()=>void run(async()=>navigate(await api!.connect(true)))}>メール送信を有効にする</button>}<p>トークで「今日のメールを探して」と話しかけてください。</p>{confirm?<div><p>Gmailとの接続を解除しますか？メールは削除されません。</p><button disabled={busy} onClick={()=>void run(async()=>{await api!.disconnect();setStatus(await api!.status());setConfirm(false);})}>Gmailの接続を解除する</button><button disabled={busy} onClick={()=>setConfirm(false)}>キャンセル</button></div>:<button className="google-disconnect" onClick={()=>setConfirm(true)}>Gmailの接続を解除</button>}</>:<button className="google-connect-action" disabled={busy||!status?.available} onClick={()=>void run(async()=>navigate(await api!.connect()))}>{busy?'Googleを開いています…':'Gmailを接続'}</button>}<p className="google-connection-note">下書きを編集し、宛先と本文を確認してから送信できます。</p>{error&&<p role="alert">{error}</p>}</section>;
}
