import { MenuPage } from '../components/MenuPage';
import {ArrowLeft,MapPin} from '@phosphor-icons/react';
import {useEffect,useState} from 'react';
import type {LifeSettings as Settings,LifeHome,GoogleSourceListResult} from '@yui/domain';
import type {LifeServicesApi} from '../life-services';
import type {GoogleCalendarTasksApi,GoogleServiceSettings} from '../google-calendar-tasks';
import '../life-services.css';
export function LifeSettings({api,googleApi,onClose,initialSection='google'}:{api:LifeServicesApi;googleApi:GoogleCalendarTasksApi;onClose:()=>void;initialSection?:'google'|'home'}){
 const [settings,setSettings]=useState<Settings|null>(null),[status,setStatus]=useState<GoogleServiceSettings|null>(null),[sources,setSources]=useState<Partial<Record<'calendar'|'tasks',GoogleSourceListResult>>>({}),[query,setQuery]=useState(''),[candidates,setCandidates]=useState<LifeHome[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[url,setUrl]=useState('');
 useEffect(()=>{let active=true;api.getSettings().then(s=>{if(active)setSettings(s);}).catch(()=>{if(active)setMessage('設定を読み込めませんでした。閉じて開き直してください。');});if(initialSection==='google')googleApi.getSettings().then(g=>{if(active)setStatus(g);}).catch(()=>{});return()=>{active=false;};},[api,googleApi]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e instanceof Error?e.message:'設定を更新できませんでした。');}finally{setBusy(false);}}
 async function save(next:Settings){setSettings(await api.saveSettings(next));setMessage('保存しました。');}
 return <MenuPage title={initialSection==='google'?'Google連携':'住んでいる地域'} onBack={onClose} backLabel={initialSection==='home'?'プロフィールへ戻る':'メニューへ戻る'} busy={busy} contentClassName="region-content">
 {!settings&&!message&&<p>設定を読み込み中…</p>}
 {settings&&initialSection==='google'&&(['calendar','tasks'] as const).map(service=><section key={service}><h3>{service==='calendar'?'Googleカレンダー':'Google Tasks'}</h3><p>{status?.[service].state==='connected'?'読み取り接続済み':'接続状態を確認してください'}</p><button disabled={busy} onClick={()=>void run(async()=>setUrl(await api.beginConnection(service,'read')))}>読み取りで接続</button><button disabled={busy} onClick={()=>void run(async()=>setUrl(await api.beginConnection(service,'write')))}>編集権限を追加</button><p>編集はトーク内の下書きを確認してから実行します。</p>{status?.[service].state==='connected'&&<button disabled={busy} onClick={()=>void run(async()=>{await googleApi.stopService(service);googleApi.sourceChoices?.set(service,null);setStatus(await googleApi.getSettings());})}>接続を解除</button>}{settings[service]===null&&googleApi.sourceChoices?.get(service)&&<button disabled={busy} onClick={()=>void run(()=>save({...settings,[service]:googleApi.sourceChoices!.get(service)}))}>この端末の参照先を同期設定に保存</button>}<p>選択中: {settings[service]?.title??'未選択'}</p><button disabled={busy||!googleApi.sources} onClick={()=>void run(async()=>{const result=await googleApi.sources!(service);setSources(old=>({...old,[service]:result}));})}>参照先を取得</button>{sources[service]?.items.map(source=><button disabled={busy} key={source.id} onClick={()=>void run(()=>save({...settings,[service]:{id:source.id,title:source.title}}))}>{source.title}を選択</button>)}{settings[service]&&<button disabled={busy} onClick={()=>void run(()=>save({...settings,[service]:null}))}>参照先の選択を解除</button>}</section>)}
 {settings&&initialSection==='home'&&<section>{settings.home&&<p className="region-current"><MapPin size={20}/>{settings.home.label}</p>}<p>市区町村や駅名で検索して、候補から選んでください。詳しい住所は不要です。</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await api.locations(query);setCandidates(result.candidates);if(!result.candidates.length)setMessage('候補が見つかりませんでした。近くの市や町の名前でも試してください。');});}}><label>地域名<input placeholder="市区町村名を入力" disabled={busy} value={query} maxLength={200} onChange={e=>{setQuery(e.target.value);setCandidates([]);}}/></label><button disabled={busy||query.trim().length<2}>{busy?'検索中…':'検索'}</button></form>{candidates.map((h,i)=><button disabled={busy} key={i} onClick={()=>void run(async()=>{await save({...settings,home:h});onClose();})}>{h.label} を選ぶ</button>)}{settings.home&&<button disabled={busy} onClick={()=>void run(()=>save({...settings,home:null}))}>保存地域を削除</button>}<p>選んだ地域の代表座標を保存します。天気や地図案内で使うための地域設定です。</p><small>地域候補：Open-Meteo / GeoNames</small></section>}
 {url&&<a href={url}>Googleの同意画面を開く</a>}{message&&<p role="status">{message}</p>}
 </MenuPage>;
}
