import { MenuPage } from '../components/MenuPage';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,SpeakerHigh} from '@phosphor-icons/react';
import type {AvatarSpeechPlayer} from '../avatar-speech';
import '../google-connections.css';
export type VoiceSettings={provider:"ttsquest"|"sakura";available:boolean;sakuraConfigured:boolean;speed?:number};
export function VoiceConnection({status,select,createPlayer,onClose}:{status:()=>Promise<VoiceSettings>;select:(provider:VoiceSettings["provider"],speed?:number)=>Promise<VoiceSettings>;createPlayer:()=>AvatarSpeechPlayer;onClose:()=>void}){
 const [settings,setSettings]=useState<VoiceSettings|null>(null);
 const [available,setAvailable]=useState<boolean|null>(null),[checking,setChecking]=useState(false),[playing,setPlaying]=useState(false),[error,setError]=useState('');
 const active=useRef(true),playback=useRef<{cancel:AbortController;player:AvatarSpeechPlayer}|null>(null);
 async function check(){setChecking(true);setError('');try{const ok=await status();if(active.current){setSettings(ok);setAvailable(ok.available);}}catch{if(active.current){setAvailable(false);setError('接続を確認できませんでした。');}}finally{if(active.current)setChecking(false);}}
 async function choose(provider:VoiceSettings["provider"],speed?:number){if(playing||checking)return;setChecking(true);setError('');try{const next=await select(provider,speed);if(active.current){setSettings(next);setAvailable(next.available);}}catch{if(active.current)setError('設定を保存できませんでした。');}finally{if(active.current)setChecking(false);}}
 function stop(){playback.current?.cancel.abort();playback.current?.player.close();playback.current=null;setPlaying(false);}
 useEffect(()=>{active.current=true;void check();return()=>{active.current=false;playback.current?.cancel.abort();playback.current?.player.close();playback.current=null;};},[status]);
 async function play(){if(playing)return;setError('');let current:NonNullable<typeof playback.current>|null=null;try{current={cancel:new AbortController(),player:createPlayer()};playback.current=current;setPlaying(true);await current.player.play('こんにちは、ずんだもんなのだ。こんな声でお話しするのだ。',current.cancel.signal);}catch{if(active.current&&!current?.cancel.signal.aborted)setError('声を再生できませんでした。接続を確認して、もう一度お試しください。');}finally{if(current&&playback.current===current){current.player.close();playback.current=null;if(active.current)setPlaying(false);}}}
 return <MenuPage title="声の設定" onBack={()=>{stop();onClose();}} contentClassName="connection-page"><div className="google-connections-content"><section className="google-connection-card"><div className="google-connection-title"><SpeakerHigh size={28}/><div><h2>ずんだもん</h2><span>{checking?'接続確認中':available?'試聴できます':'未接続'}</span></div></div><p>VOICEVOXのずんだもんの声でお話しします。</p><label htmlFor="voice-provider">音声サービス</label><select id="voice-provider" value={settings?.provider??"ttsquest"} disabled={checking||playing||!settings} onChange={e=>void choose(e.target.value as VoiceSettings["provider"])} style={{display:"block",width:"100%",padding:12,margin:"12px 0",font:"inherit",borderRadius:12}}><option value="ttsquest">TTS QUEST（WEB版VOICEVOX）</option><option value="sakura" disabled={!settings?.sakuraConfigured}>さくらのAI Engine{!settings?.sakuraConfigured?"（未設定）":""}</option></select><label htmlFor="voice-speed">話す速さ</label><select id="voice-speed" value={settings?.speed??1} disabled={checking||playing||settings?.provider!=="sakura"} onChange={e=>void choose("sakura",Number(e.target.value))} style={{display:"block",width:"100%",padding:12,margin:"12px 0",font:"inherit",borderRadius:12}}>{[0.8,0.9,1,1.1,1.2,1.3].map(speed=><option key={speed} value={speed}>{speed===1?"標準（1.0倍）":`${speed.toFixed(1)}倍`}</option>)}</select><p className="google-connection-note">{settings?.provider==="sakura"?"通常のトークとライブチャットに共通です。同じアカウントの端末にも反映されます。":"TTS QUESTは標準速度です。速さの調整は、さくらで利用できます。"}</p><p className="google-connection-note">読み上げる文章を選んだサービスへ送信します。利用制限時も、別のサービスへ自動では切り替えません。</p><button className="google-connect-action" disabled={!playing&&(checking||!available)} onClick={()=>playing?stop():void play()}>{playing?'停止':'声を試す'}</button><button className="google-disconnect" disabled={checking||playing} onClick={()=>void check()}>接続を確認</button>{available===false&&<p>音声サービスの設定を確認してください。</p>}<p className="google-connection-note">トークのスピーカーボタンで音声をONにすると、返事を読み上げます。電話ボタンからライブチャットを始められます。</p>{error&&<p role="alert">{error}</p>}</section></div></MenuPage>;
}
