import { describe, expect, it, vi } from "vitest";
import { createAudioQueue } from "../src/audio-queue";
import { TtsClientError } from "../src/tts-client";
describe("AudioQueue", () => {
  it("synthesizes and plays ordered chunks one at a time then drains", async () => { const synthesize = vi.fn(async () => new Blob(["wav"])); const play = vi.fn(async () => undefined); const drained = vi.fn(); const queue = createAudioQueue({ ttsClient: { status: async () => ({ available: true }), synthesize }, play, wait: async () => undefined, onSpeaking: vi.fn(), onListening: vi.fn(), onDrained: drained, onTerminalError: vi.fn() }); const generation = queue.beginGeneration(); queue.enqueue({ generation, index: 1, text: "二つ目" }); queue.enqueue({ generation, index: 0, text: "一つ目" }); queue.completeGeneration(generation); await vi.waitFor(() => expect(play).toHaveBeenCalledTimes(2)); expect(synthesize.mock.calls.map(([input]) => input.requestId)).toEqual(["tts:1:0", "tts:1:1"]); expect(drained).toHaveBeenCalledWith(generation); });
  it("retries an upstream failure once with the same request id", async () => { const synthesize = vi.fn().mockRejectedValueOnce(new TtsClientError("upstream")).mockResolvedValueOnce(new Blob()); const wait = vi.fn(async () => undefined); const queue = createAudioQueue({ ttsClient: { status: async () => ({ available: true }), synthesize }, play: async () => undefined, wait, onSpeaking: vi.fn(), onListening: vi.fn(), onDrained: vi.fn(), onTerminalError: vi.fn() }); const generation = queue.beginGeneration(); queue.enqueue({ generation, index: 0, text: "返事" }); queue.completeGeneration(generation); await vi.waitFor(() => expect(synthesize).toHaveBeenCalledTimes(2)); expect(wait).toHaveBeenCalledWith(250, expect.any(AbortSignal)); expect(synthesize.mock.calls.map(([input]) => input.requestId)).toEqual(["tts:1:0", "tts:1:0"]); });
  it("does not let an aborted old drain clear or drain a newer generation", async () => { const resolvers: Array<(blob: Blob) => void> = []; const synthesize = vi.fn(() => new Promise<Blob>((done) => { resolvers.push(done); })); const drained = vi.fn(); const queue = createAudioQueue({ ttsClient: { status: async () => ({ available: true }), synthesize }, play: async () => undefined, wait: async () => undefined, onSpeaking: vi.fn(), onListening: vi.fn(), onDrained: drained, onTerminalError: vi.fn() }); const old = queue.beginGeneration(); queue.enqueue({ generation: old, index: 0, text: "古い返事" }); const fresh = queue.beginGeneration(); queue.enqueue({ generation: fresh, index: 0, text: "新しい返事" }); queue.completeGeneration(fresh); await vi.waitFor(() => expect(resolvers).toHaveLength(2)); resolvers[0]!(new Blob(["old"])); resolvers[1]!(new Blob(["new"])); await vi.waitFor(() => expect(drained).toHaveBeenCalledWith(fresh)); expect(drained).not.toHaveBeenCalledWith(old); });
  it("aborts an active synthesis and discards its late WAV on interruption", async () => { let resolve!: (blob: Blob) => void; let signal: AbortSignal | undefined; const synthesize = vi.fn((_input: unknown, nextSignal: AbortSignal) => { signal = nextSignal; return new Promise<Blob>((done) => { resolve = done; }); }); const play = vi.fn(async () => undefined); const queue = createAudioQueue({ ttsClient: { status: async () => ({ available: true }), synthesize }, play, wait: async () => undefined, onSpeaking: vi.fn(), onListening: vi.fn(), onDrained: vi.fn(), onTerminalError: vi.fn() }); const generation = queue.beginGeneration(); queue.enqueue({ generation, index: 0, text: "中断される返事" }); await vi.waitFor(() => expect(signal).toBeDefined()); queue.cancelGeneration(); expect(signal?.aborted).toBe(true); resolve(new Blob(["late-wav"])); await Promise.resolve(); expect(play).not.toHaveBeenCalled(); });
  it("does not drain after a terminal invalid failure", async () => { const terminal = vi.fn(); const listening = vi.fn(); const drained = vi.fn(); const queue = createAudioQueue({ ttsClient: { status: async () => ({ available: true }), synthesize: async () => { throw new TtsClientError("invalid"); } }, play: async () => undefined, wait: async () => undefined, onSpeaking: vi.fn(), onListening: listening, onDrained: drained, onTerminalError: terminal }); const generation = queue.beginGeneration(); queue.enqueue({ generation, index: 0, text: "失敗" }); queue.completeGeneration(generation); await vi.waitFor(() => expect(terminal).toHaveBeenCalledTimes(1)); expect(listening).not.toHaveBeenCalled(); expect(drained).not.toHaveBeenCalled(); });
});
