import {render,screen,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {it,expect,vi} from 'vitest';
import {MemoryHub} from '../src/screens/MemoryHub';
import type {LifeServicesApi} from '../src/life-services';
import type {MemoryApi} from '../src/api';
import type {GoogleCalendarTasksApi} from '../src/google-calendar-tasks';
function setup(onSaveProfile?: (input:{displayName:string;occupation:string;region:string})=>Promise<void>){const settings={revision:4,home:null,calendar:null,tasks:null,personal:{nickname:'',occupation:'',details:'',responsePreferences:''}};const api={getSettings:vi.fn().mockResolvedValue(settings),saveSettings:vi.fn().mockImplementation(async s=>({...s,revision:s.revision+1}))} as unknown as LifeServicesApi;const memoryApi={list:vi.fn().mockResolvedValue([{id:'one',status:'active',sensitivity:'normal',content:'比較用の記憶'},{id:'two',status:'active',sensitivity:'sensitive',content:'表示しない秘密'}]),getSettings:vi.fn().mockResolvedValue({memoryEnabled:true,updatedAt:null}),updateSettings:vi.fn().mockImplementation(async s=>({...s,updatedAt:null}))} as unknown as MemoryApi;const onSaveName=vi.fn().mockResolvedValue(undefined),onMemoryEnabled=vi.fn();render(<MemoryHub profile={{displayName:'確認用',addressingStyle:'none',updatedAt:'2026-09-06T00:00:00Z'}} api={api} memoryApi={memoryApi} googleApi={{} as GoogleCalendarTasksApi} onClose={()=>{}} onOpenMemories={()=>{}} onSaveName={onSaveName} onSaveProfile={onSaveProfile} onMemoryEnabled={onMemoryEnabled}/>);return{api,memoryApi,onSaveName,onMemoryEnabled};}
it('saves explicit details without overwriting other settings or automatically saving on input',async()=>{const {api,onSaveName}=setup();const user=userEvent.setup();await waitFor(()=>expect(screen.getByRole('textbox',{name:'職業'})).toBeEnabled());await user.type(screen.getByRole('textbox',{name:'職業'}),'架空の職業');expect(api.saveSettings).not.toHaveBeenCalled();await user.click(screen.getByRole('button',{name:'保存する'}));await screen.findByText('保存しました。');expect(api.saveSettings).toHaveBeenCalledWith(expect.objectContaining({revision:4,calendar:null,personal:expect.objectContaining({occupation:'架空の職業'})}));expect(onSaveName).not.toHaveBeenCalled();});
it('only changes memory toggle after successful persistence',async()=>{const {memoryApi,onMemoryEnabled}=setup();const user=userEvent.setup();await waitFor(()=>expect(screen.getByRole('switch')).toBeEnabled());vi.mocked(memoryApi.updateSettings).mockRejectedValueOnce(new Error('failed'));await user.click(screen.getByRole('switch'));await screen.findByText('メモリの設定を変更できませんでした。');expect(screen.getByRole('switch')).toHaveAttribute('aria-checked','true');expect(onMemoryEnabled).not.toHaveBeenCalled();await user.click(screen.getByRole('switch'));await waitFor(()=>expect(onMemoryEnabled).toHaveBeenCalledWith(false));});
it('reports a partial name save accurately and allows retry with updated revision',async()=>{const {api,onSaveName}=setup();const user=userEvent.setup();await waitFor(()=>expect(screen.getByRole('textbox',{name:'あなたの名前'})).toBeEnabled());await user.clear(screen.getByRole('textbox',{name:'あなたの名前'}));await user.type(screen.getByRole('textbox',{name:'あなたの名前'}),'別名');onSaveName.mockRejectedValueOnce(new Error('failed'));await user.click(screen.getByRole('button',{name:'保存する'}));await screen.findByText('詳細は保存しましたが、名前を保存できませんでした。もう一度保存してください。');await user.click(screen.getByRole('button',{name:'保存する'}));await screen.findByText('保存しました。');expect(api.saveSettings).toHaveBeenLastCalledWith(expect.objectContaining({revision:5}));});

it('shows ordinary memory while keeping sensitive content hidden',async()=>{setup();expect(await screen.findByText('比較用の記憶')).toBeVisible();expect(screen.getByText('非表示の記憶')).toBeVisible();expect(screen.queryByText('表示しない秘密')).not.toBeInTheDocument();});

it('saves the connected profile without requesting legacy settings',async()=>{const save=vi.fn().mockResolvedValue(undefined);const {api}=setup(save);const user=userEvent.setup();await user.type(screen.getByRole('textbox',{name:'職業'}),'企画');await user.click(screen.getByRole('button',{name:'保存する'}));await screen.findByText('保存しました。');expect(save).toHaveBeenCalledWith({displayName:'確認用',occupation:'企画',region:''});expect(api.saveSettings).not.toHaveBeenCalled();expect(await screen.findByRole('switch')).toBeEnabled();});
