import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,statSync,symlinkSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {validate,saveConfiguration,startSetup,checkConnection} from './initial-setup.mjs';
const ai={apiKey:'sk-fictional-key-for-setup-tests-only'};
const storage={url:'https://abcdefghijklmnopqrst.supabase.co',publishableKey:'fictional-public-key',serviceKey:'fictional-server-key',origin:'https://app.example',email:'owner@example.com'};
function temp(t){const directory=mkdtempSync(join(tmpdir(),'zundamon-setup-'));t.after(()=>rmSync(directory,{recursive:true,force:true}));return join(directory,'.env.connection.local');}
async function instance(t,options={}){const target=temp(t);const app=await startSetup({target,fetcher:async()=>new Response(null,{status:200}),...options});t.after(()=>new Promise(resolve=>{app.server.close(resolve);app.server.closeAllConnections();}));return {...app,target};}
const post=(url,route,data,origin=new URL(url).origin)=>fetch(url+route,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)});
test('rejects injected values and non-Supabase destinations',()=>{for(const url of ['http://127.0.0.1','https://example.com','https://abcdefghijklmnopqrst.supabase.co.evil.test','https://abcdefghijklmnopqrst.supabase.co/path'])assert.throws(()=>validate('storage',{...storage,url}));assert.throws(()=>validate('ai',{apiKey:ai.apiKey+'\nOTHER=true'}));});
test('saves privately and never overwrites existing files or symlinks',t=>{const target=temp(t);saveConfiguration(target,ai,storage,{provider:'sakura',apiKey:'fictional-sakura'});assert.equal(statSync(target).mode&0o777,0o600);assert.match(readFileSync(target,'utf8'),/ZUNDAMON_DEFAULT_VOICE_PROVIDER="sakura"/);const original=readFileSync(target,'utf8');assert.throws(()=>saveConfiguration(target,ai,storage,{provider:'later'}));assert.equal(readFileSync(target,'utf8'),original);const other=target+'.other';writeFileSync(other,'preserve');const link=target+'.link';symlinkSync(other,link);assert.throws(()=>saveConfiguration(link,ai,storage,{provider:'later'}));assert.equal(readFileSync(other,'utf8'),'preserve');});
test('requires nonce and exact same origin',async t=>{const {url}=await instance(t);assert.equal((await fetch(new URL('/status',url))).status,403);assert.equal((await post(url,'check',{group:'ai',value:ai},'https://other.example')).status,403);});
test('connection checks send keys only to expected service and request no rows',async()=>{const requests=[];await checkConnection('storage',storage,async(url,options)=>{requests.push({url,options});return new Response(null,{status:200});});assert.equal(requests.length,4);assert.ok(requests.slice(1).every(r=>r.url.endsWith('limit=0')));assert.ok(requests.every(r=>r.options.redirect==='error'));});
test('failed connection does not authorize save and errors do not echo keys',async t=>{const {url}=await instance(t,{fetcher:async()=>new Response(null,{status:401})});const response=await post(url,'check',{group:'ai',value:ai});assert.equal(response.status,400);assert.ok(!(await response.text()).includes(ai.apiKey));assert.equal((await post(url,'save',{ai,storage,voice:{provider:'later'},prepared:true})).status,400);});
test('requires checked exact values, saves once, status never returns credentials',async t=>{const {url,target}=await instance(t);assert.equal((await post(url,'check',{group:'ai',value:ai})).status,200);assert.equal((await post(url,'check',{group:'storage',value:storage})).status,200);assert.equal((await post(url,'save',{ai:{apiKey:ai.apiKey+'changed'},storage,voice:{provider:'later'},prepared:true})).status,400);assert.equal((await post(url,'save',{ai,storage,voice:{provider:'later'},prepared:false})).status,400);assert.equal((await post(url,'save',{ai,storage,voice:{provider:'later'},prepared:true})).status,200);assert.match(readFileSync(target,'utf8'),/ZUNDAMON_SUPABASE_URL/);assert.equal((await post(url,'save',{ai,storage,voice:{provider:'later'},prepared:true})).status,409);const status=await (await fetch(url+'status')).json();assert.deepEqual(status,{configured:true,preview:false,finished:true});});
test('existing configuration blocks writes before contacting services',async t=>{let calls=0;const {url,target}=await instance(t,{fetcher:async()=>{calls++;return new Response();}});writeFileSync(target,'existing');assert.equal((await post(url,'check',{group:'ai',value:ai})).status,409);assert.equal(calls,0);assert.equal(readFileSync(target,'utf8'),'existing');});
test('preview cannot connect or save',async t=>{const {url}=await instance(t,{preview:true,fetcher:()=>{throw Error('must not run');}});assert.equal((await post(url,'check',{group:'ai',value:ai})).status,409);assert.equal((await post(url,'save',{})).status,409);});
test('Google credentials need preparation and generate an independent token key',t=>{const target=temp(t);const google={enabled:true,clientId:'fictional.apps.googleusercontent.com',clientSecret:'fictional-google-secret',prepared:false};assert.throws(()=>saveConfiguration(target,ai,storage,{provider:'later'},google));saveConfiguration(target,ai,storage,{provider:'later'},{...google,prepared:true});const env=readFileSync(target,'utf8');const token=env.match(/ZUNDAMON_GOOGLE_OAUTH_TOKEN_KEY_B64="([^"]+)"/)[1];assert.equal(Buffer.from(token,'base64').length,32);assert.match(env,/ZUNDAMON_GOOGLE_DRIVE_ENABLED="true"/);});
